// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAkH3vf9DzgHHxjcVV0e6zb-eI8UItpJww',
    appId: '1:283495436741:web:d359f5997bad4cb8efbbac',
    messagingSenderId: '283495436741',
    projectId: 'chungnam-routemaker',
    authDomain: 'chungnam-routemaker.firebaseapp.com',
    storageBucket: 'chungnam-routemaker.firebasestorage.app',
    measurementId: 'G-TGYTRS6NJX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC1xmdxkL_uQOUxIoKMWrVuwnPw20IZNug',
    appId: '1:283495436741:android:aa429b6babc7e4f1efbbac',
    messagingSenderId: '283495436741',
    projectId: 'chungnam-routemaker',
    storageBucket: 'chungnam-routemaker.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBateIH3swCCk85kgDeDnZwUKDmoZYs_gA',
    appId: '1:283495436741:ios:86d92f77847d8a5eefbbac',
    messagingSenderId: '283495436741',
    projectId: 'chungnam-routemaker',
    storageBucket: 'chungnam-routemaker.firebasestorage.app',
    iosClientId: '283495436741-nkog3veapbolj9p53ge8c6ou2ij0ij8q.apps.googleusercontent.com',
    iosBundleId: 'com.techtour.flutterprojects',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBateIH3swCCk85kgDeDnZwUKDmoZYs_gA',
    appId: '1:283495436741:ios:86d92f77847d8a5eefbbac',
    messagingSenderId: '283495436741',
    projectId: 'chungnam-routemaker',
    storageBucket: 'chungnam-routemaker.firebasestorage.app',
    iosClientId: '283495436741-nkog3veapbolj9p53ge8c6ou2ij0ij8q.apps.googleusercontent.com',
    iosBundleId: 'com.techtour.flutterprojects',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAkH3vf9DzgHHxjcVV0e6zb-eI8UItpJww',
    appId: '1:283495436741:web:db5e37599af6fa67efbbac',
    messagingSenderId: '283495436741',
    projectId: 'chungnam-routemaker',
    authDomain: 'chungnam-routemaker.firebaseapp.com',
    storageBucket: 'chungnam-routemaker.firebasestorage.app',
    measurementId: 'G-SFQCSM9DQ5',
  );
}
